title: Tyler Richard, At A Distance
description: > # this means to ignore newlines until "baseurl:"
  I'm a communications professional for non-profits. Queer. Nerdy. And an Extrovert Currently "Distancing"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://terrapax.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Tyler Richard # add your name
author-img: tyler_richard.jpg # add your photo
about-author: I'm a communications professional for non-profits. Queer. Nerdy. And an Extrovert Currently "Distancing" # add description
social-twitter: tylererichard # add your Twitter handle
social-facebook: terrapax # add your Facebook handle
# social-github:  # add your Github handle
social-linkedin: tylererichard # add your Linkedin handle
social-email: tyler@tylerrichard.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
